name: Run Task
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - name: Running
        run: |
          npm cache clean --force
          npm install
          npm run task
        env:
          TOKEN_TYPE: ${{ secrets.TOKEN_TYPE }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
          START_DATE: ${{ secrets.START_DATE }}
          NUMBER_OF_DAYS: ${{ secrets.NUMBER_OF_DAYS }}
          NODE_OPTIONS: "--max-old-space-size=8192"
